runner:
  credo: # Code Analysis
    cmd: mix credo --strict --format=flycheck
    errorformat:
      - "%f:%l:%c: %t: %m"
      - "%f:%l: %t: %m"
    level: warning
  dialyzer: # Type Checking
    cmd: mix dialyzer --format=short
    errorformat:
      - "%f:%l:%m"
    level: warning
