name: Actions

on:
  push:
    branches: [ "master" ]
    paths: [ ".github/workflows/**" ]
  pull_request:
    branches: [ "master" ]
    paths: [ ".github/workflows/**" ]

permissions:
  contents: read
  pull-requests: write

jobs:
  reviewdog-actionlint:

    name: Lint workflows
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run actionlint with reviewdog
      uses: reviewdog/action-actionlint@v1
      with:
        reporter: github-pr-review
        filter_mode: file
        fail_on_error: true
