# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Elixir CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  ELIXIR_VERSION: '1.16.0'
  OTP_VERSION: '26.0.2'

permissions:
  contents: read
  pull-requests: write

jobs:
  deps:

    name: Install dependencies
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: ${{ env.ELIXIR_VERSION }}
        otp-version: ${{ env.OTP_VERSION }}
        version-type: strict
    - name: Restore dependencies cache
      uses: actions/cache@v3
      with:
        path: deps
        key: ${{ runner.os }}-elixir-deps-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-elixir-deps-
    - run: mix deps.get
    - name: Restore build cache
      uses: actions/cache@v3
      with:
        path: _build
        key: ${{ runner.os }}-elixir-build-${{ hashFiles('**/mix.lock') }}-${{ hashFiles( '**/lib/**/*.{ex,eex}', '**/config/*.exs', '**/mix.exs' ) }}
        restore-keys: |
          ${{ runner.os }}-elixir-build-${{ hashFiles('**/mix.lock') }}-
          ${{ runner.os }}-elixir-build-
    - name: Build deps for dev
      run: mix deps.compile
    - name: Build deps for test
      run: mix deps.compile
      env:
        MIX_ENV: test

  build:

    runs-on: ubuntu-latest
    needs: deps

    steps:
    - uses: actions/checkout@v4
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: ${{ env.ELIXIR_VERSION }}
        otp-version: ${{ env.OTP_VERSION }}
        version-type: strict
    - name: Restore dependencies cache
      uses: actions/cache@v3
      with:
        path: deps
        key: ${{ runner.os }}-elixir-deps-${{ hashFiles('**/mix.lock') }}
    - name: Restore build cache
      uses: actions/cache@v3
      with:
        path: _build
        key: ${{ runner.os }}-elixir-build-${{ hashFiles('**/mix.lock') }}-${{ hashFiles( '**/lib/**/*.{ex,eex}', '**/config/*.exs', '**/mix.exs' ) }}

    - run: mix test
